### ISSUE TITLE
Switch to discord.py

### ISSUE THREAD

**Issue by Hype3808** [pogrammar/Discord-multipurpose-bot#33]
Maybe? When dpy released v2 in pypi? lol

**Comment by pogrammar** [comment]
I don't trust Danny anymore...

He resumed work after 6 months and I cant keep changing
plus I'm used to discord.ui not discord-interactions

**Comment by Hype3808** [comment]
> plus I'm used to discord.ui not discord-interactions
discord.ui is from discord.py
discord-interactions is a third party lib of discord.py

**Comment by pogrammar** [comment]
Wait whu-

**Comment by Hype3808** [comment]
what?

**Comment by Hype3808** [comment]
discord.ui implementation is from discord.py not pycord which is implemented before the day of archieve...

**Comment by pogrammar** [comment]
I got that I got it

**Comment by pogrammar** [comment]
Well im not doing it because https://github.com/Pycord-Development/guide/blob/master/docs/More/community-resources.mdx 

they put our repo as the first resource
